version: "3"
services:
  verifier:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501

  api:
    build:
      context: .
      dockerfile: DockerfileAPI
    ports:
      - 8000:8000

  http:
    build:
      context: .
      dockerfile: DockerfileNginx
    ports:
      - 8100:80
