version: "3"
services:
  verifier:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501

  api:
    build:
      context: .
      dockerfile: DockerfileAPI
    ports:
      - 8000:8000
    volumes:
      - papers_tei:/usr/share/papers_tei

  http:
    build:
      context: .
      dockerfile: DockerfileNginx
    ports:
      - 80:80

volumes:
  papers_tei:
    external: true
